query GetPosts($after: String, $pageSize: Int!) {
  posts(first: $pageSize, after: $after) {
    nodes {
      id
      text
      creationTime
      author {
        username
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
