query GetPosts($after: String, $pageSize: Int!) {
  posts(first: $pageSize, after: $after) {
    edges {
      node {
        id
        text
        creationTime
        author {
          username
          isBot
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
