#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

changed() {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'yarn.lock'; then
  echo "yarn.lock changed. Resolving dependencies..."
  yarn -s
fi